name: phylocontext
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.13
  - ncbi-datasets-cli
  - pip
  - pip:
      - click==8.1.8
      - matplotlib==3.10.1
      - numpy==2.2.3
      - pandas==2.2.3
      - pillow==11.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - seaborn==0.13.2
      - tabulate==0.9.0
      - packaging==24.2
